apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../default

components:
- ../../components/release

images:
- name: bootstrap
  newName: flomesh/fsm-bootstrap
  newTag: 0.1.1-beta4
- name: cluster-connector
  newName: flomesh/fsm-cluster-connector
  newTag: 0.1.1-beta4
- name: ingress-pipy
  newName: flomesh/fsm-ingress-pipy
  newTag: 0.1.1-beta4
- name: manager
  newName: flomesh/fsm-manager
  newTag: 0.1.1-beta4
- name: proxy-init
  newName: flomesh/fsm-proxy-init
  newTag: 0.1.1-beta4
