apiVersion: v1
kind: Service
metadata:
  name: repo-service
  namespace: flomesh
  labels:
    app.kubernetes.io/instance: repo
    app.kubernetes.io/component: repo
spec:
  ports:
  - name: repo
    port: 6060
    targetPort: repo
    protocol: TCP
  selector:
    app.kubernetes.io/instance: repo
    app.kubernetes.io/component: repo