apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.tg.configmaps.connector.name }}
  namespace: {{ include "tg.namespace" . }}
  labels:
    {{- include "traffic-guru.labels" . | nindent 4 }}
data:
  {{ .Values.tg.configmaps.connector.filename }}: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    leaderElection:
      leaderElect: true
      resourceNamespace: {{ .Values.tg.leaderElection.namespace }}
