{{- if and .Values.tg.ingress.enabled (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: pipy
  labels:
    {{- include "traffic-guru.labels" . | nindent 4 }}
spec:
  controller: flomesh.io/ingress-pipy
{{- end }}