{{- if and .Values.tg.ingress.enabled (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tg.ingress.service.name }}
  namespace: {{ include "tg.namespace" . }}
  labels:
    {{- include "traffic-guru.ingress-pipy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tg.ingress.service.type }}
  ports:
  - name: http
    port: {{ .Values.tg.ingress.service.port }}
    protocol: TCP
    targetPort: ingress
  selector:
    {{- include "traffic-guru.ingress-pipy.selectorLabels" . | nindent 4 }}
{{- end }}