apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: flomesh
  labels:
    app.kubernetes.io/instance: operator-manager
    app.kubernetes.io/component: webhook
spec:
  ports:
  - port: 443
    targetPort: 9443
    protocol: TCP
  selector:
    app.kubernetes.io/instance: operator-manager
    app.kubernetes.io/component: manager