apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fsm-role
  labels:
    helm.sh/chart: {{ include "fsm.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Chart.Name }}