apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesh-repo
  namespace: flomesh
  labels:
    app.kubernetes.io/instance: mesh-repo
    app.kubernetes.io/component: repo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: mesh-repo
      app.kubernetes.io/component: repo
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mesh-repo
        app.kubernetes.io/component: repo
    spec:
      initContainers:
      - name: wait-cert-manager
        image: flomesh/wait-for-it:1.0.0
        imagePullPolicy: IfNotPresent
        command:
        - bash
        - -c
        - |+
          /wait-for-it.sh --strict --timeout=0 \
            --host=cert-manager.cert-manager.svc \
            --port=9402 \
            -- echo "CERT-NANAGER IS READY!"
      - name: wait-cert-manager-wh
        image: flomesh/wait-for-it:1.0.0
        imagePullPolicy: IfNotPresent
        command:
        - bash
        - -c
        - |+
          /wait-for-it.sh --strict --timeout=0 \
            --host=cert-manager-webhook.cert-manager.svc \
            --port=443 \
            -- echo "CERT-NANAGER-WEBHOOK IS READY!"
      containers:
      - name: repo
        image: flomesh/pipy-pjs:0.4.0-362
        imagePullPolicy: Always
        command:
        - sh
        - -c
        - |+
          /usr/local/bin/pipy --admin-port=6060
        ports:
        - name: http
          containerPort: 6060
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20M
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
      serviceAccountName: traffic-guru
      terminationGracePeriodSeconds: 10
