apiVersion: v1
kind: Service
metadata:
  name: repo-service
  namespace: flomesh
  labels:
    app.kubernetes.io/instance: mesh-repo
    app.kubernetes.io/component: repo
spec:
  ports:
  - port: 6060
    protocol: TCP
    targetPort: 6060
  selector:
    app.kubernetes.io/instance: mesh-repo
    app.kubernetes.io/component: repo