
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: manager
    app.kubernetes.io/component: metrics-monitor
  name: manager-metrics-monitor
  namespace: flomesh
spec:
  endpoints:
    - path: /metrics
      port: https
  selector:
    matchLabels:
      app.kubernetes.io/instance: manager
      app.kubernetes.io/component: manager
---