apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: operator-manager
    app.kubernetes.io/component: metrics
  name: operator-manager-metrics-service
  namespace: flomesh
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/instance: operator-manager
    app.kubernetes.io/component: manager
---