apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-manager
  namespace: flomesh
spec:
  template:
    spec:
      containers:
      - name: manager
        args:
        - --v=5
        - --config=manager_config.yaml
        - --repo-addr=$(REPO_SERVICE_NAME).$(REPO_SERVICE_NAMESPACE).svc:6060
        - --aggregator-port=6767