apiVersion: v1
kind: Namespace
metadata:
  labels:
    flomesh.io/inject: "false"
    flomesh.io/control-plane: "true"
  name: flomesh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-manager
  namespace: flomesh
  labels:
    app.kubernetes.io/instance: operator-manager
    app.kubernetes.io/component: manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: operator-manager
      app.kubernetes.io/component: manager
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: operator-manager
        app.kubernetes.io/component: manager
    spec:
      containers:
      - name: manager
        command:
        - /operator-manager
        args:
        - --v=2
        - --config=manager_config.yaml
        image: operator-manager:latest
        imagePullPolicy: Always
        ports:
        - name: webhook
          containerPort: 9443
        - name: health
          containerPort: 8081
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 2000m
            memory: 2000Mi
          requests:
            cpu: 200m
            memory: 200Mi
      serviceAccountName: traffic-guru
      terminationGracePeriodSeconds: 30
