apiVersion: v1
kind: Namespace
metadata:
  labels:
    flomesh.io/inject: "false"
    flomesh.io/control-plane: "true"
  name: flomesh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-manager
  namespace: flomesh
  labels:
    app.kubernetes.io/instance: operator-manager
    app.kubernetes.io/component: manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: operator-manager
      app.kubernetes.io/component: manager
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: operator-manager
        app.kubernetes.io/component: manager
    spec:
      initContainers:
      - name: init
        image: flomesh/wait-for-it:1.0.0
        imagePullPolicy: IfNotPresent
        command:
        - bash
        - -c
        - |+
          /wait-for-it.sh --strict --timeout=0 \
            --host=$(REPO_SERVICE_NAME).$(REPO_SERVICE_NAMESPACE).svc \
            --port=6060 \
            -- echo "REPO IS READY!"
      - name: repo-init
        image: repo-init:latest
        imagePullPolicy: Always
        env:
        - name: REPO_SERVICE_ADDR
          value: $(REPO_SERVICE_NAME).$(REPO_SERVICE_NAMESPACE).svc:6060
        - name: BASE_CODEBASE_PATH
          value: /base
        volumeMounts:
        - mountPath: /operator
          name: operator-config
      containers:
      - command:
        - /operator-manager
        args:
        - --v=2
        image: operator-manager:latest
        imagePullPolicy: Always
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: FLOMESH_PROXY_IMAGE
          value: "flomesh/pipy-pjs:0.4.0-338"
        - name: FLOMESH_PROXY_INIT_IMAGE
          value: "flomesh/proxy-init:latest"
        - name: FLOMESH_CLUSTER_CONNECTOR_IMAGE
          value: "flomesh/cluster-connector:latest"
        - name: FLOMESH_CLUSTER_CONNECTOR_LOG_LEVEL
          value: "5"
        - name: FLOMESH_CLUSTER_CONNECTOR_CONFIG_FILE
          value: "connector_config.yaml"
        - name: FLOMESH_CLUSTER_CONNECTOR_SECRET_MOUNT_PATH
          value: "/.kube"
        - name: FLOMESH_CLUSTER_CONNECTOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: FLOMESH_CLUSTER_CONNECTOR_CONFIGMAP_NAME
          value: $(CONNECTOR_CONFIGMAP_NAME)
        - name: FLOMESH_REPO_SERVICE_ADDRESS
          value: $(REPO_SERVICE_NAME).$(REPO_SERVICE_NAMESPACE).svc:6060
        - name: FLOMESH_SERVICE_COLLECTOR_ADDRESS
          value: $(COLLECTOR_SERVICE_NAME).$(COLLECTOR_SERVICE_NAMESPACE).svc:6767
        - name: FLOMESH_OPERATOR_SERVICE_ACCOUNT_NAME
          value: $(OPERATOR_SERVICEACCOUNT_NAME)
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 200m
            memory: 100Mi
        volumeMounts:
        - name: shared-mgr-res
          mountPath: /mgr
      volumes:
      - emptyDir: {}
        name: shared-mgr-res
      - name: operator-config
        configMap:
          name: operator-config
      serviceAccountName: flomesh-service-mesh
      terminationGracePeriodSeconds: 10
