apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../default

components:
- ../../components/dev

images:
- name: manager
  newName: flomesh/fsm-manager
  newTag: dev
- name: bootstrap
  newName: flomesh/fsm-bootstrap
  newTag: dev
- name: ingress-pipy
  newName: flomesh/fsm-ingress-pipy
  newTag: dev
