{{- if and .Values.fsm.ingress.enabled (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fsm.ingress.name }}
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.ingress-pipy.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fsm.ingress-pipy.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "fsm.ingress-pipy.labels" . | nindent 8 }}
        {{- include "fsm.ingress-pipy.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: wait-repo
        image: {{ include "fsm.wait-for-it.image" . }}
        imagePullPolicy: IfNotPresent
        command:
        - bash
        - -c
        - |
          /wait-for-it.sh --strict --timeout=0 \
            --host={{- include "fsm.repo.serviceFullName" . }} \
            --port={{ .Values.fsm.services.repo.port }} \
            -- echo "REPO IS READY!"
      - name: wait-manager
        image: {{ include "fsm.wait-for-it.image" . }}
        imagePullPolicy: IfNotPresent
        command:
        - bash
        - -c
        - |
          /wait-for-it.sh --strict --timeout=0 \
            --host={{- include "fsm.webhook-service.serviceFullName" .}} \
            --port={{ .Values.fsm.services.webhook.port }} \
            -- echo "MANAGER IS READY!"
      - name: wait-aggregator
        image: {{ include "fsm.wait-for-it.image" . }}
        imagePullPolicy: IfNotPresent
        command:
        - bash
        - -c
        - |
          /wait-for-it.sh --strict --timeout=0 \
            --host={{- include "fsm.service-aggregator.serviceFullName" .}} \
            --port={{ .Values.fsm.services.aggregator.port }} \
            -- echo "AGGREGATOR IS READY!"
      containers:
      - name: ingress
        image: {{ include "fsm.ingress-pipy.image" . }}
        imagePullPolicy: {{ .Values.fsm.image.pullPolicy }}
        ports:
        - name: ingress
          containerPort: {{ .Values.fsm.ingress.service.containerPort }}
        - name: health
          containerPort: 8081
        args:
        - --v={{ .Values.fsm.logLevel }}
        - --fsm-namespace={{- include "fsm.namespace" . }}
        {{- with .Values.fsm.ingress.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        livenessProbe:
          periodSeconds: 20
          tcpSocket:
            port: {{ .Values.fsm.ingress.service.containerPort }}
        readinessProbe:
          periodSeconds: 20
          tcpSocket:
            port: {{ .Values.fsm.ingress.service.containerPort }}
        startupProbe:
          failureThreshold: 10
          initialDelaySeconds: 15
          periodSeconds: 15
          tcpSocket:
            port: {{ .Values.fsm.ingress.service.containerPort }}
      terminationGracePeriodSeconds: 60
      serviceAccountName: {{ include "fsm.serviceAccountName" . }}
      {{- with .Values.fsm.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fsm.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.fsm.affinity.enabled }}
      affinity:
        {{- with .Values.fsm.affinity.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: flomesh.io/app
                  operator: In
                  values:
                  - {{ printf "%s-%s" .Chart.Name .Values.fsm.ingress.name }}
              topologyKey: kubernetes.io/hostname
            weight: 100
      {{- end }}
      {{- with .Values.fsm.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}