apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fsm.configmaps.repoInit.name }}
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
binaryData:
  scripts.tar: |
{{ (.Files.Get "components/scripts.tar") | b64enc | indent 4}}